blank_issues_enabled: false 
contact_links:
  - name: 💬 Comunidade e Dúvidas
    url: https://github.com/asyncx-labs/gonx-forge-os/discussions
    about: Não abra Issues para dúvidas. Use a nossa aba de Discussões!
  - name: 🛡️ Reportar Vulnerabilidade (Privado)
    url: mailto:suporte@asyncx.com.br
    about: Use este canal para falhas críticas de segurança.